language: cpp

jobs:
  include:
    - os: windows
      compiler: clang
      env: NAME="windows"
    - os: windows
      compiler: gcc
      env: NAME="windows"
    - os: linux
      dist: trusty
      compiler: gcc
      env: NAME="trusty"
    - os: linux
      dist: trusty
      compiler: clang
      env: NAME="trusty"
    - os: linux
      dist: precise
      compiler: clang
      env: NAME="precise"
    - os: osx
      compiler: gcc
      env: NAME="osx"
    - os: osx
      compiler: clang
      env: NAME="osx"

before_script:
  - mkdir build && cd build

script:
  - if [[ $NAME = "trusty" OR $NAME = "precise" OR $NAME = "osx" ]]; then
    cmake ..;
    fi
  - if [[ $NAME = "windows" ]]; then
    "C:/Program Files/CMake/bin/cmake" ../CMakeLists.txt;
    fi

install:
  - if [[ $NAME = "osx" ]]; then
    brew update;
    fi
  - if [[ $NAME = "precise" ]]; then
    sudo apt-get update;
    sudo apt-get cmake-data cmake;
    fi
  - if [[ $NAME = "windows" ]]; then
    choco install cmake.install;
    "C:/Program Files/CMake/bin/cmake.exe" --version
    fi