language: cpp

matrix:
  include:
    - os: windows
      compiler: clang
    - os: windows
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
      env: NAME="trusty"
    - os: linux
      dist: trusty
      compiler: clang
      env: NAME="trusty"
    - os: linux
      dist: precise
      compiler: clang
      env: NAME="precise"

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - make

install:
  - if [[ $NAME == precise ]]; then
    sudo apt-get update;
    sudo apt-get cmake-data cmake;
    fi