language: cpp

matrix:
  include:
    - os: windows
      compiler: clang
    - os: windows
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang

#compiler:
#  - clang
#  - gcc