name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  windows:
    name: Run on Windows latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          choco install cmake
          cmake --version

      - name: Run windows.bat
        run: ./windows.bat
        shell: pwsh

      - name: Create Build Directory
        run: mkdir cmake-build-mingw-x64

      - name: Build
        run: cmake --preset "MinGW x64-debug"

      - name: Run
        run: cmake --build --preset "MinGW x64"
  linux:
    name: Run on Ubuntu latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get install cmake
          cmake --version

      - name: Run linux.sh
        run: |
          if [ ! -d "vcpkg" ]; then git clone https://github.com/Microsoft/vcpkg.git; fi
          cd vcpkg

          ./bootstrap-vcpkg.sh -disableMetrics
          ./vcpkg.exe install --recurse openssl:x64-windows sqlite3:x64-windows
          ./vcpkg integrate install

      - name: Create Build Directory
        run: mkdir cmake-build-wsl-x64

      - name: Build
        run: cmake --preset "WSL x64-debug"

      - name: Run
        run: cmake --build --preset "MinGW x64"
