name: CMake

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  windows:
    name: Run on Windows latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          choco install cmake
          cmake --version

      - uses: ashutoshvarma/setup-ninja@master

      - name: Run windows.bat
        run: ./windows.bat
        shell: pwsh
      - name: Create Build Directory
        run: mkdir cmake-build-mingw-x64

      - name: Generate Directories
        run: cmake --preset "MinGW x64-debug"

      - name: Build
        run: cmake --build --preset "MinGW x64"
