name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  job:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            windows-latest,
            ubuntu-latest,
          # macos-latest,
        ]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgPackages: 'openssl sqlite3'
            vcpkgId: 5568f110b509a9fd90711978a7cb76bae75bb092
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgPackages: 'openssl sqlite3'
            vcpkgId: 5568f110b509a9fd90711978a7cb76bae75bb092

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: lukka/get-cmake@latest

      - name: Restore artifacts / setup vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: ${{ matrix.vcpkgId }}
          vcpkhTriplet: ${{ matrix.triplet }}

      - run: '$VCPKG_ROOT/vcpkg install --recurse openssl:${{ matrix.triplet }} sqlite3:${{ matrix.triplet }}'

      - name: Run Cmake with Ninja
        uses: lukka/run-cmake@main
        with:
          cmakeListsTxtPath: '${{ github.workspace }}'
          useVcpkgToolchainFile: true
#          buildWithCMakeArgs:
