name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  linux:
    name: Build Cmake on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: download libssl-dev
        run: sudo apt-get install libssl-dev

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        run: -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  windows:
    name: Build Cmake on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake

      - name: Put MSYS2_MinGW64 on PATH
        run: echo "D:/a/_temp/msys/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create Build Directory
        run: mkdir build

#      - name: Configure Cmake
#        run: CMake configure

      - name: Build
        run: CMake --build build
